### PR TITLE
Adds ability to specify release notes to uploaded build

### LINKED ISSUE #1: Support release notes?
There doesn't seem to be a way to add release notes to an upload. AppCenter itself doesn't seem to support this in the API during the upload, it looks like it takes a separate `PUT /v0.1/apps/{owner_name}/{app_name}/releases/{release_id}` call to set `release_notes`. How hard is adding that to this step?

### PR DESCRIPTION
**Pull request by skywall**
Closes #1 

I have validated it with `bitrise test run`.

### CODE REVIEW

**Comment by skywall** [comment]
Hi @fileformat, are you ok with PR? Can you release it please?

**Comment by radimvaculik** [comment]
Oh, this is perfect change! Please, merge it! 💪

**Comment by crrobinson14** [comment]
Thank you @skywall !

**Comment by IntergalacticPenguin** [comment]
@crrobinson14 are you gonna to release it any time soon? 🤞

**Comment by crrobinson14** [comment]
@IntergalacticPenguin I am not a maintainer/contributor here, sorry. No comment.

**Comment by fileformat** [comment]
@IntergalacticPenguin  I released v1.0.1 with this update

**Comment by todor-scaleforce** [comment]
Is the v1.0.1 available in Bitrise? The feature for including release notes is still not working 😢

**Pull request merged**
